### ISSUE TITLE
mute button

### ISSUE THREAD

**Issue by alex904** [dreamcat4/lgremote#1]
Hey!

Nice app. Thanks for uploading it. It works just fine except for the mute button. Is code correct?

**Comment by dreamcat4** [comment]
If you don't mind me asking, perhaps you have changed some of the audio modes for the TV speaker in the settings screen? Using other features of the TV may alternatively give the side effect of disabling the mute key.

This application was tested to work with a (UK) LW550T-ZE model TV with firmware version 4.00.18. For that TV and firmware combination, the mute button maps to keycode 9. Here is an alternative (more verbose) listing of all the key mappings found. The valid range is from 1 up to value 255.

https://gist.github.com/1477497

As far as i am aware, these mappings should be consistently the same across all LG models. However you are welcome to try sending to the TV any of the unknown key codes, for which no response was found. Be warned however, the effect of those key codes is not known and I can't warrant for their effect(s).

**Comment by alex904** [comment]
Hi,

  Thanks for the quick response! Really great work you did. Yep, code "9"
works as a mute on my TV (47LV5500). In your Ruby project mute was "4". I did
not change modes, tv was pretty much out of the box. Don't remember exact
firmware, it was something like 4.1.xxx. If I could find a protocol
description for Samsung BD player I would be a happy guy with an app that
controls all entertainment. :) Have you heard about a forum or any meetup of
enthusiasts like you who reverse engineer remote controls? I'm lazy to do that
myself, but if nobody did that before I guess I will do that eventually. :)

------ Original Message ------
Received: 09:26 AM PST, 12/14/2011
From: Dreamcat4
reply@reply.github.com
To: alex904 alexn74@usa.net
Subject: Re: [lgremote] mute button (#1)

**Comment by dreamcat4** [comment]
Thanks for pointing that out. It seems to have been a typo in the official script. Fixed.

**Comment by alex904** [comment]
Hey,

   Sorry for bothering you again, but this thing is really driving me nuts. I
just wanted to write a simple app that tunes TV to my favorite channels with
one button click. I've understood that "change channel" interface does not
work well, because you have to know the mapping between virtual number of the
channel and its physical number. Weird design indeed. So, I've decided to send
numbers one by one instead. And I've found that even if I wait for http
response and send next digit after response came in, second digit still often
gets lost. Only way to protect it from being lost is to add a delay >200ms.
Well, with 200ms it almost always worked, but I had to increase to 0.5sec.
It's way too slow. :( I'm using a wi-fi adapter. Did you observe same behavior
from your TVset?

**Comment by dreamcat4** [comment]
LG did provide a mechanism to change the channel using 1 single command. However its pretty much useless because it requires all three of the channel parameters unless the TV will fail to perform the action and error out:

```
def change_channel assigned_no, real_no, uhf_no
  # ...
end
```

We may assumed that the TV auto-tuner normally sets the first 2 parameter assigned number == real number (by default). However even so, our remote control device (in this case our script) has no mechanism to know what this 3rd parameter should be (traditionally understood as the UHF channel frequency) - which may change between local regions within the same country, or be moved by the broadcasters whenever the Freeview / DVB channels are updated.

This is an inherent limitation set by LG's Wifi interface and API methods. The correct solution is to contact LG and to ask LG themselves to improve their `HandleChannelChange` API call. Either make it so that only one of the channel parameters is required, leaving other parameters as optional. Or for the TV to accept invalid channel information by discarding everything except for assigned_no variable. Currently, these Smart TV will not accept such invalid / partial command data and will only ever returns an error. Failing to change the channel. I really cannot do anything about this problem. If it bothers you then please contact LG and raise awareness to LG Smart TV engineers.

Otherwise, as you have already found: Sending a short sequence of 1-3 individual numbers pressed - its not ideal but at the moment the only possible solution. You can send individual keypress events by either HTTP GET/RESP or by UDP packet. By default, the script sends keypress events over TCP protocol. However that can be changed. Perhaps its worthwhile to try and switch over to using the UDP packet method.

Please see the following code:

https://github.com/dreamcat4/lgremote/blob/master/lgremote#L883-903

https://github.com/dreamcat4/lgremote/blob/master/lgremote#L935

However that solution will always incur a longer delay than the correct API method because the TV will always wait for further numerical input. This is inherently part of the direct-input channel-changing mechanism inside the TV. We cannot change this from the outside either. Therefore its still recommended to contact LG as per. to make some correction for the first solution regarding `HandleChannelChange` API call.

**Comment by alex904** [comment]
Hi,

   Thanks for the reply and all pointers. Basically we both confirmed
uselessness of "change channel" interface. :( I wish I had contacts with LG
engineers, but I don't. I suspect that in Korea physical channel numbers may
match assigned numbers. In UK and US it's not the case.
   I saw UDP interface in the code and tried to use it as well. Actually last
2 evenings I've spent few hours trying to adjust timing for short channel
number sequences for both UDP and HTTP interfaces. UDP seems to be more
responsive. However, it still works unreliably if I don't insert significant
delay (up to 0.5sec) between individual digits. I've noticed that most often
TVset "loses" second digit in the sequence. It coincides with moment when
TVset pops up the list of alternative channels matching the first digit. I'm
almost sure that engineers from LG did not bother to buffer more than one
command a time. Most likely third symbol in the sequence overrides the second
one while TVset is busy building a list of available channels. Just a
thought.
  Same thing happens with HTTP interface. Even if digits get sent after Ok
repines, they still may be lost. VolumeUp and VolumeDown work much faster over
UDP by the way.
  I'm not sure why I'm wasting so much time on this. I guess it's just matter
of principal to make it work right. :) Again, thanks for the script and the
help!

------ Original Message ------
Received: 07:15 AM PST, 01/06/2012
From: Dreamcat4
reply@reply.github.com
To: alex904 alexn74@usa.net
Subject: Re: [lgremote] mute button (#1)
